Add database
Vexvl/java-filmorate pull request #10
Opened 2023-05-17 05:30 UTC by Vexvl

2023-05-18 18:02 UTC, sergeymamonov requested changes
FilmController и др. не обязательно писать конструктор руками, если можно воспользоваться аннотацией Lombok @AllArgsConstructor? Аналогично и для других классов, где можно воспользоваться этой аннотацией.

ValidationException - это класс исключения, в нем не должно быть методов валидации. Поэтому метод validateReleaseDate нужно перенести в другой класс или создать новый класс валидатор. Валидацию необходимо вызывать из сервисе.

2023-05-18 18:02 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +/*
В проекте не должно быть закомментированного кода.

2023-05-19 02:30 UTC, Vexvl commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            commonFriends.add(userStorageDao.getUser(id));
Если честно, не совсем понятно, как методы ЮзерСервиса могут быть реализованы без цикла, ведь в любом случае нужно же получать юзеров из бд по айди

2023-05-19 11:34 UTC, sergeymamonov requested changes
Остались запросы к БД в циклах.

Задепрекейченный метод query по-прежнему используется в проекте.

2023-05-19 11:34 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmStorageDaoImp.java
> +            List<Genre> genres = getGenresByFilmId(filmId);
Запросы к БД в цикле.

2023-05-19 11:34 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserStorageDaoImp.java
> +    public List<User> getUsersByIds(List<Long> userIds) {
Этот метод где-то используется?

2023-05-19 11:34 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            friends.add(userStorageDao.getUser(id));
Запросы в цикле остались.

2023-05-19 11:34 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            commonFriends.add(userStorageDao.getUser(id));
Рекомендую разобраться в вопросе написания SQL запросов, обратиться за помощью к наставнику. В случае возникновения сложностей, пишите. Но без понимания темы SQL запросов дальше будет сложнее.

2023-05-20 19:48 UTC, sergeymamonov requested changes

2023-05-20 19:48 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmStorageDaoImp.java
> +                film.setMpa(mpaRatingDao.getMpaRatingById(filmRows.getLong("MPA_RATING_ID")));
Запрос к БД в цикле.

2023-05-20 19:48 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmStorageDaoImp.java
> +                film.setMpa(mpaRatingDao.getMpaRatingById(filmRows.getLong("MPA_RATING_ID")));
Запрос к БД в цикле.

2023-05-20 19:48 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmStorageDaoImp.java
> +                film.setMpa(mpaRatingDao.getMpaRatingById(filmRows.getLong("MPA_RATING_ID")));
Запрос к БД в цикле.

2023-05-22 14:12 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmStorageDaoImp.java
> +                film.setMpa(mpaRatingDao.getMpaRatingById(filmRows.getLong("MPA_RATING_ID")));
Запросы в цикле так и остались.

2023-05-22 14:13 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmStorageDaoImp.java
> +                film.setMpa(mpaRatingDao.getMpaRatingById(filmRows.getLong("MPA_RATING_ID")));
Остались запросы в цикле.

2023-05-22 14:20 UTC, sergeymamonov requested changes
Не исправлены все места, где выполняются запросы к БД в циклах.

2023-05-22 14:20 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmStorageDaoImp.java
> +                    MpaRating mpaRating = mpaRatingDao.getMpaRatingById(mpaRatingId);
Запросы к БД в цикле.

2023-05-23 03:54 UTC, sergeymamonov approved these changes
Описание коммитов должно быть подробно. Не должно быть несколько коммитов с одинаковым названием. В коллективной разработке, ваши коллеги будут видеть ваши коммиты, вам может потребоваться откатиться на какой-то коммит. Если они все называются одинаково, то будет сложно понять, на какой откатываться.

И исправьте оставшийся запрос в цикле.

2023-05-23 03:54 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmStorageDaoImp.java
> +                jdbcTemplate.update(insertQuery, filmId, genre.getId());
Запросы к БД в цикле.

2023-05-23 03:54 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmStorageDaoImp.java
> +    private List<Genre> getGenresByFilmId(Long filmId) {
Метод нигде не используется. Поэтому его нужно удалить.

2023-05-23 03:54 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmStorageDaoImp.java
> +    private List<Genre> updateGenres(List<Genre> genres, Long filmId) {
Обратите внимание, сначала стараются в классах размещать публичные поля, а после них приватные.

2023-05-30 23:15 UTC, merged